import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';

import 'component/lecture_box.dart';

void main() {
  runApp(const MyApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      // theme: ThemeData.dark().copyWith(
      //   scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      // ),
      home: Container(
        decoration: const BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.00, -1.00),
            end: Alignment(0, 1),
            colors: [Color(0xFF57D6FF), Colors.white],
          ),
        ),
        child: Scaffold(
          backgroundColor: Colors.transparent,
          body: ListView(children: const [
            Iphone13ProLight(),
          ]),

          // Iphone13ProLight(),
        ),
      ),
    );
  }
}

class Iphone13ProLight extends StatelessWidget {
  const Iphone13ProLight({super.key});

  @override
  Widget build(BuildContext context) {
    var width = MediaQuery.of(context).size.width;
    var height = MediaQuery.of(context).size.height;
    return Column(
      children: [
        // Container(
        //   width: width,
        //   height: height,
        //   clipBehavior: Clip.antiAlias,
        //   decoration: const BoxDecoration(
        //     gradient: LinearGradient(
        //       begin: Alignment(0.00, -1.00),
        //       end: Alignment(0, 1),
        //       colors: [Color(0xFF57D6FF), Colors.white],
        //     ),
        //   ),
        //   child: Stack(
        //     children: [
        SizedBox(
          height: height * 0.3,
        ),
        Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            Container(
              width: width * 0.1,
              height: height * 0.2,
              padding: const EdgeInsets.symmetric(vertical: 8.33),
              child: const Row(
                mainAxisSize: MainAxisSize.min,
                mainAxisAlignment: MainAxisAlignment.center,
                crossAxisAlignment: CrossAxisAlignment.center,
                children: [
                  Icon(Icons.arrow_back_ios_outlined),
                ],
              ),
            ),
            const Column(
              children: [
                SizedBox(
                  // left: 86,
                  // top: 122,
                  // height: height * 0.25,
                  // width: width * 0.5,
                  child: Text(
                    '9:17 AM',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 64,
                      fontFamily: 'Sofia Sans',
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
                Text(
                  'SUN, SEPT 17',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 48,
                    fontFamily: 'Sofia Sans',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ],
            ),
            Container(
              width: width * 0.1,
              height: height * 0.2,
              padding: const EdgeInsets.symmetric(vertical: 8.33),
              child: const Column(
                mainAxisSize: MainAxisSize.min,
                mainAxisAlignment: MainAxisAlignment.center,
                crossAxisAlignment: CrossAxisAlignment.center,
                children: [
                  Icon(Icons.arrow_forward_ios_outlined),
                ],
              ),
            ),
          ],
        ),
        SizedBox(
          height: height * 0.2,
        ),
        const LectureBox(),
      ],
      //     ),
      //   ),
      // ],
    );
  }
}
              // Positioned(
              //   left: 21,
              //   top: 450,
              //   child: SizedBox(
              //     width: 347,
              //     height: 153,
              //     child: Stack(
              //       children: [
              //         Positioned(
              //           left: 0,
              //           top: 0,
              //           child: Container(
              //             width: 347,
              //             height: 153,
              //             decoration: ShapeDecoration(
              //               color: Colors.white,
              //               shape: RoundedRectangleBorder(
              //                 side: const BorderSide(
              //                     width: 1, color: Color(0xFF7CDEFF)),
              //                 borderRadius: BorderRadius.circular(19),
              //               ),
              //             ),
              //           ),
              //         ),
              //         Positioned(
              //           left: 37,
              //           top: 8,
              //           child: SizedBox(
              //             width: 273,
              //             height: 34,
              //             child: Stack(
              //               children: [
              //                 Positioned(
              //                   left: 0,
              //                   top: 0,
              //                   child: Container(
              //                     width: 273,
              //                     height: 34,
              //                     decoration: ShapeDecoration(
              //                       color: const Color(0xFFF0F0F0),
              //                       shape: RoundedRectangleBorder(
              //                         borderRadius: BorderRadius.circular(19),
              //                       ),
              //                     ),
              //                   ),
              //                 ),
              //                 const Positioned(
              //                   left: 52,
              //                   top: 5,
              //                   child: Text(
              //                     'CURRENT LECTURE',
              //                     style: TextStyle(
              //                       color: Color(0xFFFF5A5A),
              //                       fontSize: 20,
              //                       fontFamily: 'Sofia Sans',
              //                       fontWeight: FontWeight.w600,
              //                       height: 0,
              //                     ),
              //                   ),
              //                 ),
              //               ],
              //             ),
              //           ),
              //         ),
              //         Positioned(
              //           left: 27,
              //           top: 112,
              //           child: SizedBox(
              //             width: 67,
              //             height: 24,
              //             child: Stack(
              //               children: [
              //                 Positioned(
              //                   left: 0,
              //                   top: 0,
              //                   child: Container(
              //                     width: 67,
              //                     height: 24,
              //                     decoration: ShapeDecoration(
              //                       color: const Color(0xFFF0F0F0),
              //                       shape: RoundedRectangleBorder(
              //                         borderRadius: BorderRadius.circular(19),
              //                       ),
              //                     ),
              //                   ),
              //                 ),
              //                 const Positioned(
              //                   left: 12,
              //                   top: 5,
              //                   child: Text(
              //                     '9:00 AM ',
              //                     style: TextStyle(
              //                       color: Colors.black,
              //                       fontSize: 12,
              //                       fontFamily: 'Sofia Sans',
              //                       fontWeight: FontWeight.w700,
              //                       height: 0,
              //                     ),
              //                   ),
              //                 ),
              //               ],
              //             ),
              //           ),
              //         ),
              //         Positioned(
              //           left: 254,
              //           top: 112,
              //           child: SizedBox(
              //             width: 67,
              //             height: 24,
              //             child: Stack(
              //               children: [
              //                 Positioned(
              //                   left: 0,
              //                   top: 0,
              //                   child: Container(
              //                     width: 67,
              //                     height: 24,
              //                     decoration: ShapeDecoration(
              //                       color: const Color(0xFFF0F0F0),
              //                       shape: RoundedRectangleBorder(
              //                         borderRadius: BorderRadius.circular(19),
              //                       ),
              //                     ),
              //                   ),
              //                 ),
              //                 const Positioned(
              //                   left: 12,
              //                   top: 5,
              //                   child: Text(
              //                     '10:00 AM ',
              //                     style: TextStyle(
              //                       color: Colors.black,
              //                       fontSize: 12,
              //                       fontFamily: 'Sofia Sans',
              //                       fontWeight: FontWeight.w700,
              //                       height: 0,
              //                     ),
              //                   ),
              //                 ),
              //               ],
              //             ),
              //           ),
              //         ),
              //         const Positioned(
              //           left: 174,
              //           top: 52,
              //           child: Text(
              //             '(VBM)',
              //             style: TextStyle(
              //               color: Colors.black,
              //               fontSize: 40,
              //               fontFamily: 'Sofia Sans',
              //               fontWeight: FontWeight.w200,
              //               height: 0,
              //             ),
              //           ),
              //         ),
              //         const Positioned(
              //           left: 89,
              //           top: 52,
              //           child: Text(
              //             'FDS',
              //             style: TextStyle(
              //               color: Colors.black,
              //               fontSize: 40,
              //               fontFamily: 'Sofia Sans',
              //               fontWeight: FontWeight.w700,
              //               height: 0,
              //             ),
              //           ),
              //         ),
              //         Positioned(
              //           left: 114,
              //           top: 100,
              //           child: SizedBox(
              //             width: 120,
              //             height: 48,
              //             child: Stack(
              //               children: [
              //                 Positioned(
              //                   left: 0,
              //                   top: 2,
              //                   child: Container(
              //                     width: 120,
              //                     height: 44,
              //                     decoration: ShapeDecoration(
              //                       color: const Color(0xFFF0F0F0),
              //                       shape: RoundedRectangleBorder(
              //                         borderRadius: BorderRadius.circular(19),
              //                       ),
              //                     ),
              //                   ),
              //                 ),
              //                 const Positioned(
              //                   left: 16,
              //                   top: 0,
              //                   child: Text(
              //                     'B301',
              //                     style: TextStyle(
              //                       color: Color(0xFF001E8B),
              //                       fontSize: 40,
              //                       fontFamily: 'Sofia Sans',
              //                       fontWeight: FontWeight.w400,
              //                       height: 0,
              //                     ),
              //                   ),
              //                 ),
              //               ],
              //             ),
              //           ),
              //         ),
              //       ],
              //     ),
              //   ),
              // ),
              // Positioned(
              //   left: 68,
              //   top: 302,
              //   child: SizedBox(
              //     width: 253,
              //     height: 111.55,
              //     child: Stack(
              //       children: [
              //         Positioned(
              //           left: 0,
              //           top: 0,
              //           child: Container(
              //             width: 253,
              //             height: 111.55,
              //             decoration: ShapeDecoration(
              //               color: Colors.white,
              //               shape: RoundedRectangleBorder(
              //                 side: const BorderSide(
              //                     width: 1, color: Color(0xFF7CDEFF)),
              //                 borderRadius: BorderRadius.circular(19),
              //               ),
              //             ),
              //           ),
              //         ),
              //         Positioned(
              //           left: 26.98,
              //           top: 5.83,
              //           child: SizedBox(
              //             width: 199.05,
              //             height: 24.79,
              //             child: Stack(
              //               children: [
              //                 Positioned(
              //                   left: 0,
              //                   top: 0,
              //                   child: Container(
              //                     width: 199.05,
              //                     height: 24.79,
              //                     decoration: ShapeDecoration(
              //                       color: const Color(0xFFF0F0F0),
              //                       shape: RoundedRectangleBorder(
              //                         borderRadius: BorderRadius.circular(19),
              //                       ),
              //                     ),
              //                   ),
              //                 ),
              //                 const Positioned(
              //                   left: 38.02,
              //                   top: 4.17,
              //                   child: SizedBox(
              //                     width: 123.22,
              //                     height: 17.50,
              //                     child: Text(
              //                       'PREVIOUS LECTURE',
              //                       style: TextStyle(
              //                         color: Color(0xFFFF8900),
              //                         fontSize: 13,
              //                         fontFamily: 'Sofia Sans',
              //                         fontWeight: FontWeight.w600,
              //                         height: 0,
              //                       ),
              //                     ),
              //                   ),
              //                 ),
              //               ],
              //             ),
              //           ),
              //         ),
              //         Positioned(
              //           left: 19.69,
              //           top: 81.66,
              //           child: SizedBox(
              //             width: 48.85,
              //             height: 17.50,
              //             child: Stack(
              //               children: [
              //                 Positioned(
              //                   left: 0,
              //                   top: 0,
              //                   child: Container(
              //                     width: 48.85,
              //                     height: 17.50,
              //                     decoration: ShapeDecoration(
              //                       color: const Color(0xFFF0F0F0),
              //                       shape: RoundedRectangleBorder(
              //                         borderRadius: BorderRadius.circular(19),
              //                       ),
              //                     ),
              //                   ),
              //                 ),
              //                 const Positioned(
              //                   left: 11.31,
              //                   top: 5.34,
              //                   child: SizedBox(
              //                     width: 32.08,
              //                     height: 10.21,
              //                     child: Text(
              //                       '8:00 AM ',
              //                       style: TextStyle(
              //                         color: Colors.black,
              //                         fontSize: 7,
              //                         fontFamily: 'Sofia Sans',
              //                         fontWeight: FontWeight.w700,
              //                         height: 0,
              //                       ),
              //                     ),
              //                   ),
              //                 ),
              //               ],
              //             ),
              //           ),
              //         ),
              //         Positioned(
              //           left: 185.19,
              //           top: 81.66,
              //           child: SizedBox(
              //             width: 48.85,
              //             height: 17.50,
              //             child: Stack(
              //               children: [
              //                 Positioned(
              //                   left: 0,
              //                   top: 0,
              //                   child: Container(
              //                     width: 48.85,
              //                     height: 17.50,
              //                     decoration: ShapeDecoration(
              //                       color: const Color(0xFFF0F0F0),
              //                       shape: RoundedRectangleBorder(
              //                         borderRadius: BorderRadius.circular(19),
              //                       ),
              //                     ),
              //                   ),
              //                 ),
              //                 const Positioned(
              //                   left: 10.81,
              //                   top: 4.34,
              //                   child: SizedBox(
              //                     width: 36.46,
              //                     height: 10.21,
              //                     child: Text(
              //                       '9:00 AM ',
              //                       style: TextStyle(
              //                         color: Colors.black,
              //                         fontSize: 7,
              //                         fontFamily: 'Sofia Sans',
              //                         fontWeight: FontWeight.w700,
              //                         height: 0,
              //                       ),
              //                     ),
              //                   ),
              //                 ),
              //               ],
              //             ),
              //           ),
              //         ),
              //         const Positioned(
              //           left: 122,
              //           top: 39,
              //           child: SizedBox(
              //             width: 71.45,
              //             height: 35,
              //             child: Text(
              //               '(DSW)',
              //               style: TextStyle(
              //                 color: Colors.black,
              //                 fontSize: 26,
              //                 fontFamily: 'Sofia Sans',
              //                 fontWeight: FontWeight.w200,
              //                 height: 0,
              //               ),
              //             ),
              //           ),
              //         ),
              //         const Positioned(
              //           left: 65,
              //           top: 40,
              //           child: SizedBox(
              //             width: 51.04,
              //             height: 35,
              //             child: Text(
              //               'CDT',
              //               style: TextStyle(
              //                 color: Colors.black,
              //                 fontSize: 26,
              //                 fontFamily: 'Sofia Sans',
              //                 fontWeight: FontWeight.w700,
              //                 height: 0,
              //               ),
              //             ),
              //           ),
              //         ),
              //         Positioned(
              //           left: 83.12,
              //           top: 74.37,
              //           child: SizedBox(
              //             width: 87.49,
              //             height: 36.63,
              //             child: Stack(
              //               children: [
              //                 Positioned(
              //                   left: 0,
              //                   top: 0,
              //                   child: Container(
              //                     width: 87.49,
              //                     height: 32.08,
              //                     decoration: ShapeDecoration(
              //                       color: const Color(0xFFF0F0F0),
              //                       shape: RoundedRectangleBorder(
              //                         borderRadius: BorderRadius.circular(19),
              //                       ),
              //                     ),
              //                   ),
              //                 ),
              //                 const Positioned(
              //                   left: 15.88,
              //                   top: 1.63,
              //                   child: SizedBox(
              //                     width: 63.43,
              //                     height: 35,
              //                     child: Text(
              //                       'B301',
              //                       style: TextStyle(
              //                         color: Color(0xFF001E8B),
              //                         fontSize: 26,
              //                         fontFamily: 'Sofia Sans',
              //                         fontWeight: FontWeight.w400,
              //                         height: 0,
              //                       ),
              //                     ),
              //                   ),
              //                 ),
              //               ],
              //             ),
              //           ),
              //         ),
              //       ],
              //     ),
              //   ),
              // ),
              // Positioned(
              //   left: 68,
              //   top: 639,
              //   child: SizedBox(
              //     width: 253,
              //     height: 111.55,
              //     child: Stack(
              //       children: [
              //         Positioned(
              //           left: 0,
              //           top: 0,
              //           child: Container(
              //             width: 253,
              //             height: 111.55,
              //             decoration: ShapeDecoration(
              //               color: Colors.white,
              //               shape: RoundedRectangleBorder(
              //                 side: const BorderSide(
              //                     width: 1, color: Color(0xFF7CDEFF)),
              //                 borderRadius: BorderRadius.circular(19),
              //               ),
              //             ),
              //           ),
              //         ),
              //         Positioned(
              //           left: 26.98,
              //           top: 5.83,
              //           child: SizedBox(
              //             width: 199.05,
              //             height: 24.79,
              //             child: Stack(
              //               children: [
              //                 Positioned(
              //                   left: 0,
              //                   top: 0,
              //                   child: Container(
              //                     width: 199.05,
              //                     height: 24.79,
              //                     decoration: ShapeDecoration(
              //                       color: const Color(0xFFF0F0F0),
              //                       shape: RoundedRectangleBorder(
              //                         borderRadius: BorderRadius.circular(19),
              //                       ),
              //                     ),
              //                   ),
              //                 ),
              //                 const Positioned(
              //                   left: 62.02,
              //                   top: 3.17,
              //                   child: SizedBox(
              //                     width: 85,
              //                     height: 17,
              //                     child: Text(
              //                       'NEXT LECTURE',
              //                       style: TextStyle(
              //                         color: Color(0xFF00FF66),
              //                         fontSize: 13,
              //                         fontFamily: 'Sofia Sans',
              //                         fontWeight: FontWeight.w600,
              //                         height: 0,
              //                       ),
              //                     ),
              //                   ),
              //                 ),
              //               ],
              //             ),
              //           ),
              //         ),
              //         Positioned(
              //           left: 19.69,
              //           top: 81.66,
              //           child: SizedBox(
              //             width: 48.85,
              //             height: 17.50,
              //             child: Stack(
              //               children: [
              //                 Positioned(
              //                   left: 0,
              //                   top: 0,
              //                   child: Container(
              //                     width: 48.85,
              //                     height: 17.50,
              //                     decoration: ShapeDecoration(
              //                       color: const Color(0xFFF0F0F0),
              //                       shape: RoundedRectangleBorder(
              //                         borderRadius: BorderRadius.circular(19),
              //                       ),
              //                     ),
              //                   ),
              //                 ),
              //                 const Positioned(
              //                   left: 11.31,
              //                   top: 5.34,
              //                   child: SizedBox(
              //                     width: 32.08,
              //                     height: 10.21,
              //                     child: Text(
              //                       '10:15 AM ',
              //                       style: TextStyle(
              //                         color: Colors.black,
              //                         fontSize: 7,
              //                         fontFamily: 'Sofia Sans',
              //                         fontWeight: FontWeight.w700,
              //                         height: 0,
              //                       ),
              //                     ),
              //                   ),
              //                 ),
              //               ],
              //             ),
              //           ),
              //         ),
              //         Positioned(
              //           left: 185.19,
              //           top: 81.66,
              //           child: SizedBox(
              //             width: 48.85,
              //             height: 17.50,
              //             child: Stack(
              //               children: [
              //                 Positioned(
              //                   left: 0,
              //                   top: 0,
              //                   child: Container(
              //                     width: 48.85,
              //                     height: 17.50,
              //                     decoration: ShapeDecoration(
              //                       color: const Color(0xFFF0F0F0),
              //                       shape: RoundedRectangleBorder(
              //                         borderRadius: BorderRadius.circular(19),
              //                       ),
              //                     ),
              //                   ),
              //                 ),
              //                 const Positioned(
              //                   left: 10.81,
              //                   top: 4.34,
              //                   child: SizedBox(
              //                     width: 36.46,
              //                     height: 10.21,
              //                     child: Text(
              //                       '11:15 AM ',
              //                       style: TextStyle(
              //                         color: Colors.black,
              //                         fontSize: 7,
              //                         fontFamily: 'Sofia Sans',
              //                         fontWeight: FontWeight.w700,
              //                         height: 0,
              //                       ),
              //                     ),
              //                   ),
              //                 ),
              //               ],
              //             ),
              //           ),
              //         ),
              //         const Positioned(
              //           left: 122,
              //           top: 39,
              //           child: SizedBox(
              //             width: 71.45,
              //             height: 35,
              //             child: Text(
              //               '(VSG)',
              //               style: TextStyle(
              //                 color: Colors.black,
              //                 fontSize: 26,
              //                 fontFamily: 'Sofia Sans',
              //                 fontWeight: FontWeight.w200,
              //                 height: 0,
              //               ),
              //             ),
              //           ),
              //         ),
              //         const Positioned(
              //           left: 65,
              //           top: 40,
              //           child: SizedBox(
              //             width: 51.04,
              //             height: 35,
              //             child: Text(
              //               'CAO ',
              //               style: TextStyle(
              //                 color: Colors.black,
              //                 fontSize: 26,
              //                 fontFamily: 'Sofia Sans',
              //                 fontWeight: FontWeight.w700,
              //                 height: 0,
              //               ),
              //             ),
              //           ),
              //         ),
              //         Positioned(
              //           left: 83.12,
              //           top: 74.37,
              //           child: SizedBox(
              //             width: 87.49,
              //             height: 36.63,
              //             child: Stack(
              //               children: [
              //                 Positioned(
              //                   left: 0,
              //                   top: 0,
              //                   child: Container(
              //                     width: 87.49,
              //                     height: 32.08,
              //                     decoration: ShapeDecoration(
              //                       color: const Color(0xFFF0F0F0),
              //                       shape: RoundedRectangleBorder(
              //                         borderRadius: BorderRadius.circular(19),
              //                       ),
              //                     ),
              //                   ),
              //                 ),
              //                 const Positioned(
              //                   left: 15.88,
              //                   top: 1.63,
              //                   child: SizedBox(
              //                     width: 63.43,
              //                     height: 35,
              //                     child: Text(
              //                       'B107',
              //                       style: TextStyle(
              //                         color: Color(0xFF001E8B),
              //                         fontSize: 26,
              //                         fontFamily: 'Sofia Sans',
              //                         fontWeight: FontWeight.w400,
              //                         height: 0,
              //                       ),
              //                     ),
              //                   ),
              //                 ),
              //               ],
              //             ),
              //           ),
              //         ),
              //       ],
              //     ),
              //   ),
              // ),
              
              // const Positioned(
              //   left: 57,
              //   top: 201,
              //   child: Text(
              //     'SUN,',
              //     style: TextStyle(
              //       color: Colors.white,
              //       fontSize: 48,
              //       fontFamily: 'Sofia Sans',
              //       fontWeight: FontWeight.w600,
              //       height: 0,
              //     ),
              //   ),
              // ),
              // const Positioned(
              //   left: 179,
              //   top: 201,
              //   child: Text(
              //     'SEPT 17',
              //     style: TextStyle(
              //       color: Colors.white,
              //       fontSize: 48,
              //       fontFamily: 'Sofia Sans',
              //       fontWeight: FontWeight.w600,
              //       height: 0,
              //     ),
              //   ),
              // ),
              // const Positioned(
              //   left: 158,
              //   top: 201,
              //   child: Text(
              //     ',',
              //     style: TextStyle(
              //       color: Colors.white,
              //       fontSize: 48,
              //       fontFamily: 'Sofia Sans',
              //       fontWeight: FontWeight.w600,
              //       height: 0,
              //     ),
              //   ),
              // ),
              // Positioned(
              //   left: 0,
              //   top: 161,
              //   child: Container(
              //     width: 40,
              //     height: 40,
              //     padding: const EdgeInsets.symmetric(vertical: 8.33),
              //     child: const Row(
              //       mainAxisSize: MainAxisSize.min,
              //       mainAxisAlignment: MainAxisAlignment.center,
              //       crossAxisAlignment: CrossAxisAlignment.center,
              //       children: [
              //         Icon(Icons.arrow_back_ios_outlined),
              //       ],
              //     ),
              //   ),
              // ),
              // Positioned(
              //   left: 353,
              //   top: 161,
              //   child: Container(
              //     width: 37,
              //     height: 40,
              //     padding: const EdgeInsets.symmetric(vertical: 8.33),
              //     child: const Column(
              //       mainAxisSize: MainAxisSize.min,
              //       mainAxisAlignment: MainAxisAlignment.center,
              //       crossAxisAlignment: CrossAxisAlignment.center,
              //       children: [
              //         Icon(Icons.arrow_forward_ios_outlined),
              //       ],
              //     ),
              //   ),
              // ),
 
