import 'package:flutter/material.dart';
import 'package:timetable_app/home_screen.dart';

void main() {
  runApp(
    const MyApp(),
  );
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: SafeArea(
        child: Container(
          decoration: const BoxDecoration(
            gradient: LinearGradient(
              begin: Alignment(0.00, -1.00),
              end: Alignment(0, 1),
              colors: [Color(0xFF57D6FF), Colors.white],
            ),
          ),
          child: const Scaffold(
            backgroundColor: Colors.transparent,
            body: HomeScreen(),
          ),
        ),
      ),
    );
  }
}
